name: 'Terraform'

on:
  push:
    branches: main
    paths: remediations/**
  pull_request:
    branches: main
    paths: remediations/**
    
permissions:
  contents: read  

env:
  AWS_REGION: us-east-1
  INIT_PARAMETERS: -backend-config="bucket=secure-pipeline-aws-state" -backend-config="key=state/terraform.tfstate" -backend-config="region=us-east-1" -backend-config="use_lockfile=true"

jobs:
  plan:
    permissions:
      contents: read
      id-token: write
      pull-requests: write

    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./remediations

    steps:
    - name: Checkout
      uses: actions/checkout@v7

    - name: Setup TFLint
      uses: terraform-linters/setup-tflint@v6

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v6.3.0
      with:
        aws-region: ${{ env.AWS_REGION }}
        role-to-assume: ${{ secrets.ARN_ROLE }}
        role-session-name: gha-pipeline-aws-${{ github.run_id }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v4

    - name: Terraform Init
      run: terraform init ${{ env.INIT_PARAMETERS }}

    - name: Terraform Format
      run: terraform fmt -check
      continue-on-error: true

    - name: Terraform Validate
      run: terraform validate
     
    - name: Init TFLint
      if: github.event_name == 'pull_request'
      run: tflint --init
      
    - name: Run TFLint
      if: github.event_name == 'pull_request'
      run: tflint -f compact

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color -input=false -out=tfplan

    - name: Upload Plan Artifact
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v7
      with:
        name: tfplan
        path: ./remediations/tfplan
        retention-days: 7

    - name: Checkov Scan
      if: github.event_name == 'pull_request'
      uses: bridgecrewio/checkov-action@master
      id: checkov
      with:
        directory: ./remediations
        quiet: true
        soft_fail: true
        output_format: cli
        output_file_path: checkov
        framework: terraform


    - name: Comment plan on PR
      uses: actions/github-script@v9
      if: github.event_name == 'pull_request'
      with:
        script: |
          const body = `#### Terraform Plan — \`${{ steps.plan.outcome }}\`
          <details><summary>Show plan</summary>

            \`\`\`terraform
            ${{ steps.plan.outputs.stdout }}
            \`\`\`
            </details>`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body
            })

    - name: Comment Checkov report on PR
      uses: actions/github-script@v9
      if: github.event_name == 'pull_request'
      with:
        script: |
         const out = require('fs').readFileSync('checkov/results_cli.txt', 'utf8');
          const body = `#### Checkov Scan — \`${{ steps.checkov.outcome }}\`
          <details><summary>Show results</summary>

          \`\`\`
          ${out}
          \`\`\`
          </details>`;
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body
          })

  apply:
    
    environment: production
    needs: plan
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    permissions:
      contents: read
      id-token: write
           
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./remediations

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Download Plan Artifact
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/download-artifact@v8
        with:
          name: tfplan
          path: ./remediations

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.3.0
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.ARN_ROLE }}
          role-session-name: gha-pipeline-aws-${{ github.run_id }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4

      - name: Terraform Init
        run: terraform init ${{ env.INIT_PARAMETERS }}

      - name: Apply reviewed plan
        run: terraform apply -input=false tfplan